### ISSUE TITLE
Trying to build BuildXL myself and get error DX0500

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/BuildXL#1226]
I am trying to build BuildXL myself and I am getting following output with error code DX0500:
# bxl.cmd -all
Preparing to build.
> BuildXL Selfhost wrapper - run 'domino -SelfhostHelp' for more info
Building using the LKG (published NuGet package) version of BuildXL.
Server mode enabled.
C:\Users\RustedWizard\Downloads\BuildXL-master\BuildXL-master\Out\BootStrap\Microsoft.BuildXL.win-x64.0.1.0-20191115.0\RunInSubst.exe B=C:\Users\RustedWizard\Downloads\BuildXL-master\BuildXL-master B:\Out\BootStrap\Microsoft.BuildXL.win-x64.0.1.0-20191115.0\bxl.exe /config:B:\config.dsc /IncrementalScheduling /nowarn:909 /nowarn:11318 /nowarn:11319 /unsafe_IgnorePreloadedDlls- /historicMetadataCache+ /cachemiss /cacheSessionName:20191116_17220258-RUSTEDLAPTOP-RustedWizard@RUSTEDLAPTOP /remotetelemetry /reuseOutputsOnDisk+ /scrubDirectory:B:\out\objects /storeFingerprints /cacheMiss /p:[Sdk.BuildXL]useQTest=true /logsToRetain:20 /environment:SelfhostLKG /unsafe_GlobalUntrackedScopes:B:\Shared\Tools /unsafe_GlobalPassthroughEnvVars:NUGET_CREDENTIALPROVIDERS_PATH /generateCgManifestForNugets:B:\cg\nuget\cgmanifest.json /cacheConfigFilePath:B:\Out\Cache\CacheCore.json /server /serverDeploymentDir:B:\Out\Selfhost\LKG.ServerDeployment /Interactive+ /f:~(tag='LongRunningTest') /substTarget:B:\ /substSource:C:\Users\RustedWizard\Downloads\BuildXL-master\BuildXL-master\  /logProcessDetouringStatus+ /logProcessData+ /logProcesses+
Microsoft (R) Build Accelerator. Build: 0.1.0-20191115.0, Version: [refs/heads/master:8d3b4b7ab856660441964431129d5815e9cb9acb]
Copyright (C) Microsoft Corporation. All rights reserved.

[0:00] -- Telemetry is enabled. SessionId: a3571f3d-0000-0000-bd07-15dbb7160fcb
[0:00] -- Using pip filter: ~(tag='LongRunningTest')
[2:22] warning DX0268: [PipC9BDB264245A25D5, pwsh.exe, BuildXL.Explorer, App.app, {targetRuntime:"win-x64"}] Pip completed successfully, but with file monitoring violations. It will not be stored to the cache, since its declared inputs or outputs may be inaccurate.
[2:40] error DX0500: [PipC9BDB264245A25D5, pwsh.exe, BuildXL.Explorer, App.app, {targetRuntime:"win-x64"}] - Disallowed file accesses were detected (R = read, W = write):
Disallowed file accesses performed by: C:\Users\RustedWizard\Downloads\BuildXL-master\BuildXL-master\out\frontend\Download\PowerShell.Core.win-x64\c\pwsh.exe
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Accounts\1.6.2\Az.Accounts.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Advisor\1.0.1\Az.Advisor.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Aks\1.0.2\Az.Aks.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.AnalysisServices\1.1.1\Az.AnalysisServices.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.ApiManagement\1.3.1\Az.ApiManagement.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.ApplicationInsights\1.0.2\Az.ApplicationInsights.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Automation\1.3.3\Az.Automation.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Batch\1.1.1\Az.Batch.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Billing\1.0.1\Az.Billing.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Cdn\1.3.1\Az.Cdn.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.CognitiveServices\1.2.1\Az.CognitiveServices.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Compute\2.6.0\Az.Compute.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.ContainerInstance\1.0.1\Az.ContainerInstance.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.ContainerRegistry\1.1.0\Az.ContainerRegistry.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.DataFactory\1.3.0\Az.DataFactory.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.DataLakeAnalytics\1.0.1\Az.DataLakeAnalytics.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.DataLakeStore\1.2.2\Az.DataLakeStore.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.DeploymentManager\1.0.1\Az.DeploymentManager.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.DevTestLabs\1.0.0\Az.DevTestLabs.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Dns\1.1.1\Az.Dns.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.EventGrid\1.2.2\Az.EventGrid.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.EventHub\1.4.0\Az.EventHub.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.FrontDoor\1.1.1\Az.FrontDoor.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.HDInsight\2.0.2\Az.HDInsight.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.IotHub\1.3.0\Az.IotHub.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.KeyVault\1.3.1\Az.KeyVault.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.LogicApp\1.3.1\Az.LogicApp.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.MachineLearning\1.1.1\Az.MachineLearning.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.ManagedServices\1.0.1\Az.ManagedServices.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.MarketplaceOrdering\1.0.1\Az.MarketplaceOrdering.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Media\1.1.0\Az.Media.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Monitor\1.3.0\Az.Monitor.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Network\1.14.0\Az.Network.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.NotificationHubs\1.1.0\Az.NotificationHubs.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.OperationalInsights\1.3.3\Az.OperationalInsights.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.PolicyInsights\1.1.3\Az.PolicyInsights.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.PowerBIEmbedded\1.1.0\Az.PowerBIEmbedded.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.RecoveryServices\1.4.5\Az.RecoveryServices.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.RedisCache\1.1.0\Az.RedisCache.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Relay\1.0.2\Az.Relay.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Resources\1.7.0\Az.Resources.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.ServiceBus\1.4.0\Az.ServiceBus.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.ServiceFabric\1.2.0\Az.ServiceFabric.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.SignalR\1.1.0\Az.SignalR.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Sql\1.14.2\Az.Sql.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.StorageSync\1.2.0\Az.StorageSync.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Storage\1.7.0\Az.Storage.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.StreamAnalytics\1.0.0\Az.StreamAnalytics.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.TrafficManager\1.0.2\Az.TrafficManager.psd1
 R  C:\Users\RustedWizard\Documents\PowerShell\Modules\Az.Websites\1.4.2\Az.Websites.psd1

R  = Read
[4:28] 100.00%  Processes:[989 done (944 hit), 985 succeeded, 1 failed, 3 skipped, 0 executing, 0 waiting] Files:[36432/36432]
[4:28] -- Cache savings: 95.45% of 989 included processes. 0 excluded via filtering.
Build FAILED
    Log Directory: C:\Users\RustedWizard\Downloads\BuildXL-master\BuildXL-master\out\Logs\20191116-172203
The BuildXL build failed with exit code 1

Any form of help/tip are appreciated!

**Comment by inforithmics** [comment]
I would build bxl with minimal setting (less can go wrong), Because bxl -all although builds the unit Tests. 
bxl.cmd -minimal

**Comment by mmiller-msft** [comment]
Look at the PSMODULEPATH environment variable.  Remove any entries that aren't in C:\Program Files\WindowsPowerShell\Modules or C:\windows\system32\WindowsPowerShell\v1.0\Modules.  BuildXL runs tasks in a sandbox and verifies all files read and written to but you've told PowerShell to enumerate other directories to look for extensions.  Reducing the environment variable will limit it to just the 'official' modules.  These powershell module extensions are 'bad' in that they can occasionally change the behavior or a powershell script (good/ok when it adds new functionality, less good if it changes/breaks existing functionality).
