### ISSUE TITLE
Quickbuild cannot be found in the PATH env variable after VSIX install

### ISSUE THREAD

**Issue by jespergustinmsft** [microsoft/BuildXL#1272]
Got tipped inside Visual Studio to install the 1ES Build Assistant, so I did. But after downloading and installing the VSIX package and running a build, the following message shows up in the 1ES Build Assistant log in VS:

1ES Build Assistant is being initialized.
1ES Build Assistant is not supported. Quickbuild cannot be found in the PATH env variable.

**Comment by mpysson** [comment]
The 1ES Build Assistant and Quickbuild are unrelated to the code in this repository. I'll follow up in a direct message with a pointer to area owners for that.
