### ISSUE TITLE
DScript Documentation.

### ISSUE THREAD

**Issue by ScatteredRay** [microsoft/BuildXL#1273]
I've been using BuildXL to run some local builds on our CMake project. And it's been helpful, I'd like to further explore BuildXL and it seems that DScript has the most expressive bindings into the system. However there seems to be nearly zero public documentation on DScript, and few samples. Additional documentation for getting started with DScript would be greatly appreciated.

**Comment by mpysson** [comment]
Documentation added in 6b4fc7a637e203db09eccb6db4d8e328a883139d

**Comment by ScatteredRay** [comment]
This is great! Thanks!
