### ISSUE TITLE
Tags for new releases are missing in BuildXL repository

### ISSUE THREAD

**Issue by nikola-sh** [microsoft/BuildXL#1281]
Page [Release-Notes.md](https://github.com/microsoft/BuildXL/blob/master/Documentation/Wiki/Release-Notes.md) has information about new BuildXL releases, but corresponding repository tags are missing.
So it is not clear which revision I should build to get tested production-ready build.

**Comment by marcelolynch** [comment]
Hi @nikola-sh, we've addressed this in our release pipeline and the tags for the prod versions (which correspond to the release notes) will be pushed starting next week. This week's release (which would be tagged `Prod-0.1.0-20210107.0`), corresponds to commit f49ee4061bed3f871aa6f635e9d1bdc4307081a9.
