### ISSUE TITLE
NLog AzureBlobStorageLogTarget and OptimizeBufferReuse

### ISSUE THREAD

**Issue by snakefoot** [microsoft/BuildXL#1283]
Instead of doing this:

https://github.com/microsoft/BuildXL/blob/fd36f586726888561c385e3f30e68e4fd853e81b/Public/Src/Cache/Logging/Library/External/AzureBlobStorageLogTarget.cs#L58-L61

Then it should be like this:

```c#
public AzureBlobStorageLogTarget(AzureBlobStorageLog log)
{
     _log = log;
     _log.OnFileOpen = WriteHeaderAsync;
     _log.OnFileClose = WriteFooterAsync;
     this.OptimizeBufferReuse = true;
}

protected override void Write(LogEventInfo logEvent) 
{ 
     // RenderLogEvent() + OptimizeBufferReuse = true will skip StringBuilder-allocation
     _log.Write(RenderLogEvent(this.Layout, logEvent));
} 
```

Then you can remove `LowAllocationSimpleLayout`. See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target

Also notice that NLog 4.7.7 reduces memory-allocation with 10-20 pct (Compared to older versions of NLog).

Also notice that NLog 4.6.8 has better support for async-api by introducing AsyncTaskTarget. See also https://github.com/NLog/NLog/wiki/How-to-write-a-custom-async-target

**Comment by snakefoot** [comment]
@SergeyTeplyakov NLog 5.0 will make `OptimizeBufferReuse = true` by default, but one is still required to use `RenderLogEvent`.

**Comment by SergeyTeplyakov** [comment]
@snakefoot Thanks a lot for pointing this out. I checked in my changes already but I revert them and will use `OptimizeBufferReuse`.

I'll update our code base to use the flag and will update to the latest NLog version.

**Comment by snakefoot** [comment]
Resolved by Merged PR 599075 https://github.com/microsoft/BuildXL/commit/e645f01d989ef9ea001cd96adc27be28f3b1ad23
