### ISSUE TITLE
error DX0064: [Pip56CACF840947E197, DBS.QTest.exe (CloudBuild QTest), ...

### ISSUE THREAD

**Issue by xiaoxiao-Xu** [microsoft/BuildXL#1290]
I am building Office project with using 'ohome build debug x64 nosmart corephase nobackup nosync maxdomino', but I hit a error message as below. **Could anyone help to look at the issue and how can I fix the issue?** Thanks in advance.

============================== Domino ProductBuild ==============================
error DX0064: [Pip56CACF840947E197, DBS.QTest.exe (CloudBuild QTest), oneservice_x64_debug, qtest.qtest.rn.18047653495166817346, {} || {Running QTest for D:\Office\Target\x64\debug\oneservice\x-none\hierarchy\microsoft.office.onenote.sync.hierarchy.unittests.dll (QTest|oneservice|x64_debug|oneservice\sync\hierarchy\src\unittests)}, D:\Office\Build\ProductBuild\dsc\oneservice_x64_debug\spec.1.dsc, D:\Office\Build\DominoTemp\y\1\ka4zb00xvkgc6c5h86je519c\sandbox] - failed with exit code 1
Running Dbs.QTest.exe --testBinary D:\Office\Target\x64\debug\oneservice\x-none\hierarchy\microsoft.office.onenote.sync.hierarchy.unittests.dll --runner MsTest_150 --qTestLogsDir D:\Office\Logs\QTest\oneservice_x64_debug\qtest_qtest_rn_18047653495166817346 --qtestPlatform X64 --buildPlatform X64 --qtestDotNetFramework Framework45 --qTestRetryOnFailureMode Full --qTestBuildType agnostic --testSourceDir oneservice\sync\hierarchy\src\unittests --buildSystem BuildXL --qTestExcludeCcTargetsFile D:\Office\dev\otools\inc\test\qTestExcludeCcTargets-mstest.txt --QTestFlakyTestManagementSuppressionFile D:\Office\dev\otools\inc\test\CloudBuild.FlakyTests.json --sandbox D:\Office\Build\DominoTemp\y\1\ka4zb00xvkgc6c5h86je519c\sandbox\qtest --copyToSandbox D:\Office\Build\x64\debug\oneservice\sync\Hierarchy\src\UnitTests\objd\x64 --qCodeCoverageEnumType None
Skipping results upload.
Log directory: D:\Office\Logs\QTest\oneservice_x64_debug\qtest_qtest_rn_18047653495166817346\attempt1

**Comment by mpysson** [comment]
Taking this conversation internal since it is specific to the office codebase
