### ISSUE TITLE
BuildXL Visual Studio Integration doesn't support multi-target project

### ISSUE THREAD

**Issue by Elderry** [microsoft/BuildXL#1291]
### Steps to reproduce
1. Have a multi-target C# project with csproj file of SDK style, including:
```
<TargetFrameworks>net48;net5.0</TargetFrameworks>
```
And there is one `build.cmd` file in the same directory as .sln file.

2. Right click the project in Solution Explorer and click `Build`

### Expected behavior
The build process got redirected to `build.cmd` and process the script.

### Actual behavior
The build process seems takes over by vanilla MSBuild.

### Some thought
I think this is caused by the project type support status of BuildXL. [From this code](https://github.com/microsoft/BuildXL/blob/master/Public/Src/IDE/VsIntegration/BuildXLVsPackage/BuildXLVsPackage.cs#L511-L517) I see that currently CsProj and VcxProj are supported. For multi-target project, or in other words, .NET Core project, has a different project GUID `9A19103F-16F7-4668-BE54-9A1E7A4F7556` as [claimed in this page](https://github.com/dotnet/project-system/blob/main/docs/opening-with-new-project-system.md#project-type-guids). We want BuildXL to remain its behavior for .NET Core projects. Is there any backlog to do this?

**Comment by mpysson** [comment]
Moving this issue to an internal discussion.
