### ISSUE TITLE
Unclear how to build BuildXL for Linux

### ISSUE THREAD

**Issue by kjczarne** [microsoft/BuildXL#1302]
Hi,

The documentation states that one needs a Windows machine in order to build BuildXL for Linux and then it refers to a broken link.
I'm talking specifically about [this section](https://github.com/microsoft/BuildXL/blob/master/Documentation/Wiki/DeveloperGuide.md#build-and-test-for-linux).

The broken link that is being referred to is: https://github.com/microsoft/BuildXL/blob/master/Documentation/Wiki/Wiki/LinuxDevelopment/How_to_test.md

Is the support for Linux completely not there? Can I get some basic instructions on whether and how I could test distributed builds on Linux?

**Comment by pgunasekara** [comment]
Hi @kjczarne. Sorry about the slow response to this issue! We have updated our Linux builds recently, you can now build on Linux with this command under the BuildXL repo root: `./bxl.sh -minimal`

Please let me know if you hit any issues with that. Additionally, I will update the documentation for building on Linux very soon as well.

**Comment by kjczarne** [comment]
Thanks @pgunasekara I will try it out on Monday. Really happy to see Linux builds are now supported on Linux 😊
