### ISSUE TITLE
When Ninja Added BuildXL option, error CX0000005 was reported when using VS2022 to test the project.

### ISSUE THREAD

**Issue by KirenLi** [microsoft/BuildXL#1305]
We use Debug Information Format's ZI build option when building our project using buildXL and ninja. One of the third-party libraries we use, fakeit, is reporting an error during test. Error code: Cx00000005, this third-party library must apply the ZI option.
We have been troubled by this for a long time, hope to get help on this again, thanks.
Fakeit link:https://github.com/eranpeer/FakeIt

**Comment by pgunasekara** [comment]
Thanks for reporting this issue! Since you are working with Marcelo on a fix for this, I will close out this Github issue.
