### ISSUE TITLE
Update documentation needed for Visual studio 2022

### ISSUE THREAD

**Issue by VincentBailly** [microsoft/BuildXL#1313]
The prerequisite part of the developers' documentation tells to install "Visual Studio 2019 Build Tools".
The link provided in the documentation only allows to download "Build Tools for Visual Studio 2022".
The document should either be updated to tell to use the 2022 version, or the link should be updated to a page where we can download the appropriate version.

[BuildXL](https://github.com/microsoft/BuildXL)/[Documentation](https://github.com/microsoft/BuildXL/tree/main/Documentation)/[Wiki](https://github.com/microsoft/BuildXL/tree/main/Documentation/Wiki)/DeveloperGuide.md

**Comment by pgunasekara** [comment]
Thanks for reporting this! We will push out updated docs soon.
