### ISSUE TITLE
Setting up a distributed build with the public version

### ISSUE THREAD

**Issue by zharpaz-bmc-com** [microsoft/BuildXL#1319]
Hi,
I am trying to set up a distributed build with the public version of BuildXl. I have two questions:

1. Is the cache functionality available with the public version?
2. How can I get an example of command-line invocations, (with the configuration files) of a distributed build environment?

Thanks,
  Ziv

**Comment by mpysson** [comment]
Hi Ziv,

Both of your questions are answered in issue #1310

**Comment by zharpaz-bmc-com** [comment]
Hi @mpysson ,
Thank you for your answer.

Is it possible to run a distributed build with the cache disabled? (So it will work with always performing the build?)

**Comment by mpysson** [comment]
Distributed builds use the cache for file transport between machines. So a distributed build will not currently work with the cache layer disabled.
