### ISSUE TITLE
buildXL fail on Assertion failed (runningPips == 0): There are still pips at running 

### ISSUE THREAD

**Issue by gangoll** [microsoft/BuildXL#1320]
Hello,
I am running vs project with buildXL with msbuild resolvers.
in the project, I am using project references to another project.
the issue is when I run the project it builds the references project successfully and the build fail with the error:

critical DX0059: Catastrophic BuildXL Failure.
Build:[Developer Build].
Exception:System.Diagnostics.ContractsLight.ContractException: Assertion failed (runningPips == 0): There are still pips at running state at the end of the build.
        at \.\Public\Src\Engine\Scheduler\Scheduler.cs:1666
   at void System.Diagnostics.ContractsLight.ContractRuntimeHelper.ReportFailure(ContractFailureKind kind, string msg, string conditionTxt, Provenance provenance) in C:/Sources/GitHub/RuntimeContracts/src/RuntimeContracts/ContractRuntimeHelper.cs:line 20.....

Thanks

**Comment by semihokur** [comment]
Please let us know if this commit a273745 does not fix the issue.

**Comment by mpysson** [comment]
Closing this as the Microsoft internal instances of this failure have all been fixed.
