### ISSUE TITLE
Getting error while trying to build the Hello World MsBuild Example

### ISSUE THREAD

**Issue by Ashish-Gautam-22** [microsoft/BuildXL#1321]
Hi, I am trying to understand how to use BuildXL for a project.- I have complied the code to generate the bxl.exe using bxl.cmd -minimal command Just to test I wanted to Build the example file. When I do I get the following error. 

`D:\Software\BuildXL\Examples\MsBuildHelloWorld>build.bat
D:\Software\BuildXL\Examples\MsBuildHelloWorld>D:\Software\BuildXL\/bxl /c:config.bc /disableProcessRetryOnResourceExhaustion+
Preparing to build.> BuildXL Selfhost wrapper - run 'domino -SelfhostHelp' for more info
Building using the LKG (published NuGet package) version of BuildXL.
Server mode enabled.
D:\Software\BuildXL\Out\BootStrap\Microsoft.BuildXL.win-x64.0.1.0-20230407.6\bxl.exe /runInSubst /IncrementalScheduling /nowarn:909 /nowarn:11318 /nowarn:11319 /unsafe_IgnorePreloadedDlls- /historicMetadataCache+ /cachemiss /cacheSessionName:20230412_16410891-AD005-z004rz5a@IMW1015313C /unsafe_GlobalUntrackedScopes:\"C:\Program Files\WindowsApps\" /remotetelemetry /reuseOutputsOnDisk+ /enableEvaluationThrottling /p:[Sdk.BuildXL]useQTest=true /logsToRetain:20 /environment:SelfhostLKG /unsafe_GlobalUntrackedScopes:\"C:\Users\Z004RZ5A\.nuget\plugins\netfx\CredentialProvider.Microsoft\" /unsafe_GlobalPassthroughEnvVars:NUGET_CREDENTIALPROVIDERS_PATH /remoteCacheCutoff+ /remoteCacheCutoffLength:2 /generateCgManifestForNugets:B:\cg\nuget\cgmanifest.json /CacheMiss:[commite9542d7e824cf2c43af33e0c06ffde2696a30552:commit146a83c37bf3df4dcd6654f9fe428f2ce4c444d5:commitf6076099dbebde2a6aec9797e83bf287ea1bd2f1] /cacheConfigFilePath:B:\Out\Cache\CacheCore.json /server /serverDeploymentDir:B:\Out\Selfhost\LKG.ServerDeployment /Interactive+ /f:~(dpt(spec='private\Guests\WDG\*'))and~((spec='Public\Src\Cache\*'))and~(tag='LongRunningTest')and~(spec='Public\Src\Deployment\cache.nugetpackages.dsc')and~(spec='Public\src\Deployment\privatePackages.dsc')and~(spec='Public\src\Deployment\ide.dsc')and~(spec='Public\src\Deployment\tests.dsc') /c:config.bc /disableProcessRetryOnResourceExhaustion+ /substTarget:B: /substSource:D:\Software\BuildXL  /logProcessDetouringStatus+ /logProcessData+ /logProcesses+
Microsoft (R) Build Accelerator. Build: 0.1.0-20230407.6, Version: [refs/heads/main:d9962376ca23679ca6d8162a6103226bb86aced9]
Copyright (C) Microsoft Corporation. All rights reserved.
[0:03] error DX14415: Output 'D:\Software\BuildXL\Out\VS\object\Example' is declared outside any known mount. Please consider declaring a writable mount that contains the output.
D:\Software\BuildXL\examples\msbuildhelloworld\Example.vcxproj(0,0): error DX11414: A failure occurred while scheduling a pip. Reason: Failed to schedule the pip.
Build FAILED
    Log Directory: D:\Software\BuildXL\examples\msbuildhelloworld\Out\Logs\20230412-164109
The BuildXL build failed with exit code -1
D:\Software\BuildXL\Examples\MsBuildHelloWorld>`

The error code is DX14415, any help on how to resolve or what I am doing wrong?

**Comment by smera** [comment]
Hi,
BuildXL is using the [Microsoft.Build.Prediction](https://www.nuget.org/packages/Microsoft.Build.Prediction) library to get some evaluation-time predictions about where an MSBuild project is going to produce outputs into. In this case it seems that the prediction is wrong, and `D:\Software\BuildXL\Out\VS\object\Example` is a location which doesn't have a policy that allows writes. One option would be to add a configuration mount on that location with write permissions, but I think the easiest is to update the example project with explicit locations where the intermediates and final binaries are going to go E.g.: you could change Example.vcxproj to add `OutDir` and `IntermediateOutputPath` as follows:

Example.vcxproj
```
...
<PropertyGroup>
    <ConfigurationType>Application</ConfigurationType>
    <PlatformToolset>v143</PlatformToolset>
    <OutDir>Bin\</OutDir>
    <IntermediateOutputPath>Object\</IntermediateOutputPath>
  </PropertyGroup>
...
```
I'll apply a fix to the example to reflect this as well.

Thanks,
Serge.

**Comment by Ashish-Gautam-22** [comment]
Thanks @smera , this solved the issue I was facing but I am now facing other issues. Will open a separate issue for the same.
