### ISSUE TITLE
DetoursServices: PathFromObjectAttributesViaId causes offline files to be recalled

### ISSUE THREAD

**Issue by lhallam** [microsoft/BuildXL#1329]
When a process running under DetoursServices opens a file by ID, PathFromObjectAttributesViaId opens the same file with GENERIC_READ. This causes our minifilter to fetch file contents over the network, even when the detoured call includes FILE_OPEN_NO_RECALL (or only requests e.g. READ_ATTRIBUTES, which would not trigger a recall).

Tested with Microsoft.BuildXL.win-x64 0.1.0-20231122.3

Could this be changed to either not request GENERIC_READ (I think READ_ATTRIBUTES should suffice for GetFinalPathByHandle(?)) or pass FILE_OPEN_NO_RECALL?

Thanks,
Lewis.

**Comment by pgunasekara** [comment]
Thanks for reporting this @lhallam! We are looking into this issue for you now.

**Comment by narasamdya** [comment]
@lhallam , yes you're right, `FILE_READ_ATTRIBUTES` should be sufficient for `GetFinalPathByHandle`.

This [commit ](https://github.com/microsoft/BuildXL/commit/4fb8e7ce07d243ccd95de0d66da551538a794493) should fix the issue. Please do verify it on your end.

**Comment by lhallam** [comment]
Confirmed fixed, thank you!
