### ISSUE TITLE
error DX11233: Hexadecimal digit expected

### ISSUE THREAD

**Issue by chadsugithub** [microsoft/BuildXL#1330]
buildxl.win-x64 version 0.1.0-20231208.1

It seems that BuildXL thinks `\x` starts an escape sequence for a hexadecimal value and can't process the following properly.

```
@@public
export const dscriptToBinaryGraphEvaluationProperties= [
    "VCToolsArm=d:\xtc\.A\microsoft.spo.vccompiler.iiakpedploakrz5fdzn-7cdytamzhv8ehqkkkjy0mxw\lib\native\bin\hostx64\arm",
    "VCToolsArm64=d:\xtc\.A\microsoft.spo.vccompiler.iiakpedploakrz5fdzn-7cdytamzhv8ehqkkkjy0mxw\lib\native\bin\hostx64\arm64",
    "VCToolsChpe=d:\xtc\.A\microsoft.spo.vccompiler.iiakpedploakrz5fdzn-7cdytamzhv8ehqkkkjy0mxw\lib\native\bin\hostx64\chpe",
    "VCToolsX64=d:\xtc\.A\microsoft.spo.vccompiler.iiakpedploakrz5fdzn-7cdytamzhv8ehqkkkjy0mxw\lib\native\bin\hostx64\x64",
    "VCToolsX86=d:\xtc\.A\microsoft.spo.vccompiler.iiakpedploakrz5fdzn-7cdytamzhv8ehqkkkjy0mxw\lib\native\bin\hostx64\x86",
];
```

Starting task 'Domino Enlist Build' started [ 01:09:46 PM ] prep done in 0.302s
E:\spocore\Build\EnlistBuild\dsc\EnlistmentBuildRunner.dsc(11, 21): error DX11233: Hexadecimal digit expected.
E:\spocore\Build\EnlistBuild\dsc\EnlistmentBuildRunner.dsc(12, 23): error DX11233: Hexadecimal digit expected.
E:\spocore\Build\EnlistBuild\dsc\EnlistmentBuildRunner.dsc(13,22): error DX11233: Hexadecimal digit expected.
E:\spocore\Build\EnlistBuild\dsc\EnlistmentBuildRunner.dsc(14,21): error DX11233: Hexadecimal digit expected.
E:\spocore\Build\EnlistBuild\dsc\EnlistmentBuildRunner.dsc(15, 21): error DX11233: Hexadecimal digit expected.
[0:00] error DX11230: One or more error occurred during parsing. See output for more details.

[EnlistmentBuildRunner.dsc.txt](https://github.com/microsoft/BuildXL/files/13983450/EnlistmentBuildRunner.dsc.txt)

**Comment by pgunasekara** [comment]
Followed up offline about this issue. This is expected since \ is used for escape characters in typescript.
