### ISSUE TITLE
MSBuild - BuildXL Fails to Reference Correct Dependency Folder in Release Mode

### ISSUE THREAD

**Issue by Zo11** [microsoft/BuildXL#1336]
**Issue Summary:**
I'm encountering an issue when building a Visual Studio C++ solution in Release mode. The build fails with an error message indicating a missing dependency in the Debug folder, even though the dependency is correctly added to project references.

**Steps to Reproduce:**

1. **Open Visual Studio 2019**
2. **Create a New Project:**
   - Type: Empty project
   - Project name: `BuildXLDependency`
   - Location: `E:\buildxl_test`
3. **Create a Static Library Project:**
   - File -> Add -> New Project...
   - Type: Empty project
   - Project name: `MyLib`
   - Location: `E:\buildxl_test\BuildXLDependency`
4. **Configure MyLib:**
   - In Solution Explorer, right-click `MyLib`
   - Click `Properties`
   - Under `Configuration`, select `All Configurations`
   - Under `Platform`, select `All Platforms`
   - Navigate to `Configuration Properties` -> `General`
   - Set `Configuration Type` to `Static Library (.lib)`
   - Click `OK`
5. **Add Files to MyLib:**
   - Right-click `MyLib` -> `Add` -> `New Item...`
   - Name: `MyClass.h`
   - Location: `E:\buildxl_test\BuildXLDependency\MyLib`
   - Repeat for `MyClass.cpp`
6. **Add Code to MyLib:**
   - **MyClass.h:**
     ```cpp
     #pragma once
     class MyClass
     {
     public:
         void sayHello();
     };
     ```
   - **MyClass.cpp:**
     ```cpp
     #include "MyClass.h"
     #include <iostream>
     void MyClass::sayHello()
     {
         std::cout << "Hello from MyLib" << std::endl;
     }
     ```
7. **Add a File to BuildXLDependency and Call sayHello():**
   - Right-click `BuildXLDependency` -> `Add` -> `New Item...`
   - Name: `Source.cpp`
   - Location: `E:\buildxl_test\BuildXLDependency`
   - Add the following code to `Source.cpp`:
     ```cpp
     #include "MyClass.h"
     int main()
     {
         MyClass myClass;
         myClass.sayHello();
         return 0;
     }
     ```
8. **Make BuildXLDependency Depend on MyLib:**
   - In Solution Explorer, right-click the `References` option under `BuildXLDependency`
   - Click `Add Reference...`
   - Check the `MyLib` box
   - Click `OK`
   - Right-click `BuildXLDependency` and click `Properties`
   - Ensure `All Configurations` and `All Platforms` are selected
   - Navigate to `C/C++` under `Configuration Properties`
   - Add `MyLib` to `Additional Include Directories`
   - Click `OK`
9. **Rename x86 to Win32:**
   - In Solution Explorer, right-click `Solution BuildXLDependency`
   - Click `Configuration Manager...`
   - Click the `Active solution platform` dropdown
   - Click `<Edit...>`
   - Select `x86` and click `Rename` to `Win32`
   - File -> Save All
10. **Build Release x64 Using Visual Studio**
    - Ensure everything works so far.
11. **BuildXL Configuration:**
    - Create the following BuildXL config:
      ```
      config({
          qualifiers: {
              defaultQualifier: {Configuration: "Debug", Platform: "Win32"}
          },
          resolvers: [
              {
                  kind: "MsBuild",
                  root: d`.`,
                  fileNameEntryPoints: [
                      r`BuildXLDependency.sln`,
                  ],
                  moduleName: "BuildXLDependency",
                  msBuildSearchLocations: [d`C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin`],
                  useLegacyProjectIsolation: true
              }
          ]
      });
      ```
12. **Build with BuildXL:**
    - Before building, due to this issue: https://github.com/microsoft/BuildXL/issues/719, add this to BuildXLDependency.vcxproj
      ```xml
      <ItemGroup>
        <ProjectReferenceTargets Include="Build" Targets="Build" />
      </ItemGroup>
      ```
    - Attempt to build using BuildXL.
    - If successful, change the default qualifier to `Release Win32` and build again.

**Expected Behavior:**
Build should reference the correct dependency in the Release folder.

**Actual Behavior:**
Build fails with the error:
```
LINK : fatal error LNK1181: cannot open input file 'E:\buildxl_test\BuildXLDependency\Debug\MyLib.lib' [E:\buildxl_test\BuildXLDependency\BuildXLDependency.vcxproj]
```

**Additional Information:**
In my attempts to generate these steps I tried the above 3 times, and the last time the error messages were different. If for some reason Release Win32 builds, try Release x64. That one fails with different error messages but a similar problem, missing dependencies.

**Comment by smera** [comment]
Hello,
The error seems to be coming from the linker itself (which seems to say it cannot find the mentioned file). BuildXL honors the build graph MSBuild returns without interfering with tool behavior. Have you tried building your solution with MSBuild itself? (outside of BuildXL). In order to debug this, I'd also recommend running with `keepProjectGraphFile: true` in the resolver configuration settings to make sure the project dependencies are as expected. This option will leave a json file under `Out/frontend/MSBuild` describing the build graph that MSBuild produced.

Thanks,
Serge.

**Comment by Zo11** [comment]
Yes, everything works perfectly with MSBuild. For some reason BuildXL is getting confused. I unfortunately no longer have time to look into this, so I'll close the issue. If someone else runs into this in the future maybe they can reopen the issue and provide better details than me.
