### ISSUE TITLE
Add Visual Studio 2022 Professional Support

### ISSUE THREAD

**Issue by desdesdes** [microsoft/BuildXL#1340]
When you have Visual Studio 2022 Professional installed and not Visual Studio 2022 Enterprise buildxl will not find the build tools.

**Comment by desdesdes** [comment]
Fixed in https://github.com/microsoft/BuildXL/pull/1339. Can someone please review & merge?

**Comment by pgunasekara** [comment]
Thanks for your contribution @desdesdes! As our github repository is a mirror, we cherry pick PRs from github into our internal repo. However, it looks like for whatever reason github didn't credit you as the author, sorry about that! The merged change can be found here: https://github.com/microsoft/BuildXL/commit/66c5403a18b77e5767933dd0c145fc461619c218
