### ISSUE TITLE
Is MsBuild C++ project (vcxproj) supported on Linux?

### ISSUE THREAD

**Issue by Wizmann** [microsoft/BuildXL#1342]
I encountered an issue when trying to build the "HelloWorldCPP" example using the following command on Ubuntu 22.04 (WSL2):

```bash
~/BuildXL/bxl.sh --config config.dsc
```

The error message I received was:

```
error DX11200: Resolver kind 'MsBuild' is not registered; registered resolvers are DScript, SourceResolver, DefaultSourceResolver, Nuget, Download, Rush, Yarn, CustomJavaScript, Lage, Ninja.
```

Does BuildXL support building "vcxproj" projects on Linux? Specifically, is it possible to use MsBuild as the frontend and gcc/clang as the backend?

If not, do you have a plan for that?

**Comment by pgunasekara** [comment]
Hi @Wizmann, thanks for trying BuildXL. Currently we do not support the MsBuild resolver on Linux.
