### ISSUE TITLE
Invalid package link for nuget package (OSX)?

### ISSUE THREAD

**Issue by benkeen** [microsoft/BuildXL#1344]
I tried building the app on MacOSX as per the [instructions here](https://github.com/microsoft/BuildXL/blob/main/Documentation/Wiki/DeveloperGuide.md#macos) but the nuget download would fail when running `./bxl.sh`:

> Package 'Microsoft.BuildXL.osx-x64 0.1.0-20241120.7' is not found in the following primary source(s): '/Users/[me]/.nuget/packages/,https://pkgs.dev.azure.com/mseng/PipelineTools/_packaging/BuildXL.External/nuget/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly.

Looks like maybe the package is now called `Interop.Runtime.osx-x64` (?) so updating [this line](https://github.com/microsoft/BuildXL/blob/main/bxl.sh#L24) did allow the package to download, but failed on later steps.

**Comment by pgunasekara** [comment]
Hi @benkeen, unfortunately we no longer actively support macos. I can verify why the package isn't being pushed to that feed, but it's possible that things won't work even if you get the bootstrap package.

**Comment by benkeen** [comment]
No worries, thanks @pgunasekara.
