### ISSUE TITLE
Migrate VS extension to AsyncPackage

### ISSUE THREAD

**Issue by wjk** [microsoft/BuildXL#163]
[Per this documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019), the VS IDE extension should be migrated to use `AsyncPackage` and background autoloading. I tried to do this myself, but it would not compile (and I suspect that even if it did, I would introduce subtle threading bugs). If this could be addressed, I would appreciate it, because VS2019 nags me at launch about using the deprecated synchronous load mechanism. Thanks!

**Comment by dannyvv** [comment]
Hi @wjk,

Agree we need to update. For now it should work fine when ignoring the warning.

**Comment by rongjiecomputer** [comment]
@wjk What did you do to make the VS IDE extension run in VS 2019? I installed it, dismiss the performance warning, but C# Intellisense still doesn't seem to work.

**Comment by wjk** [comment]
@rongjiecomputer In all honesty, I didn't actually try that. I removed the extension right after I saw the performance warning. IMHO, BuildXL is a fascinating curiosity, but nowhere near ready for use on real projects (at least, outside of Microsoft). Sorry I wasn't able to help!

**Comment by almiliMSFT** [comment]
Addressed in PR #516
