### ISSUE TITLE
NuGet package deployment

### ISSUE THREAD

**Issue by matkoch** [microsoft/BuildXL#28]
When would you consider to publish NuGet packages for the sandboxing implementation? As a side question: currently it seems this only supports Windows and macOS. Any plans for Linux?

PS: It's great to see something like this is being worked on. Thanks!

**Comment by erikma** [comment]
Quite right that it's a missing piece of the puzzle. It's in our (MS-internal) backlog leading to the release of the full Build Accelerator codebase in this repo next calendar year. We punted that item for this release as the effort is better spent on that next release, getting not only the sandbox code out but a more complete solution where the sandboxing tech is just a part of the whole.

Keeping this issue open for tracking so we can resolve when we get it committed.

**Comment by 986253417** [comment]
how to  build BuildXL locally from the master branch of its repo. anyone explain a little more specific. thanks

**Comment by matkoch** [comment]
@erikma any news on this? I'm still waiting to finally integrate BuildXL for its sandboxing feature into my project.

**Comment by mpysson** [comment]
Sorry for a very delayed response. BuildXL and its sandboxing now work on Ubuntu 20.04
