### ISSUE TITLE
Linux sandboxing and build support

### ISSUE THREAD

**Issue by erikmav** [microsoft/BuildXL#29]
Regarding the Linux question from #28: We definitely know it's needed, but it's not the max priority for some time yet. It would be ideal to have parity across all three OSes but for internal teams that we support it has not bubbled up to the top of the ask list.

**Comment by 986253417** [comment]
the file of the path of BuildXL-master\Shared\Scripts\bxl.cmd , it's content :" powershell -NoProfile -ExecutionPolicy RemoteSigned %~dp0\Bx1.ps1 '=#singlequote# , " cannot execute success. first i change the Bxl.ps1 to bxl.ps1. then it will thrown out : The string is missing the terminator: ' . + CategoryInfo : ParserError:<;=:> [], parentContainsErrorRecordException

**Comment by mpysson** [comment]
Sorry for a very delayed response. BuildXL and its sandboxing now work on Ubuntu 20.04
