### ISSUE TITLE
Example for MSBuild support

### ISSUE THREAD

**Issue by wjk** [microsoft/BuildXL#308]
Similarly to #282, I would appreciate an example on how to integrate MSBuild projects (both csproj and vcxproj, if possible) into BuildXL. Thanks!

**Comment by jbayardo** [comment]
The methodology is exactly the same as in the example repository, the only difference is the resolver that must be called.

To adapt the example in the repository, you just have to change `kind` to `"MsBuild"`, remove `buildDirectory`, and that would make BuildXL build as if you had run `msbuild` from the root of your project (of course, you also have to add your proj file).

For additional configuration options, you can check https://github.com/microsoft/BuildXL/blob/master/Public/Sdk/Public/Prelude/Prelude.Configuration.Resolvers.dsc#L98 .

Please note that MSBuild support requires VS 2019 (which as of today is in Preview), and `sln` files are not supported.

**Comment by bgianfo** [comment]
Yes Please! This would be very useful.

**Comment by wjk** [comment]
@bgianfo Bizarrely, there used to be an example posted as a comment on this issue, but it seems to have been deleted.

**Comment by AndyGerlicher** [comment]
@wjk looks like you're right. Here's the comment for posterity (from my email):

> The methodology is exactly the same as in the example repository, the only difference is the resolver that must be called.
> To adapt the example in the repository, you just have to change kind to "MsBuild", remove buildDirectory, and that would make BuildXL build as if you had run msbuild from the root of your project (of course, you also have to add your proj file).
> For additional configuration options, you can check https://github.com/microsoft/BuildXL/blob/master/Public/Sdk/Public/Prelude/Prelude.Configuration.Resolvers.dsc#L98 .
> Please note that MSBuild support requires VS 2019 (which as of today is in Preview), and sln files are not supported.

Not sure why it was deleted other than we're working on a better answer for this.

In the meantime, I'll add a few things. We have [another repo](https://github.com/microsoft/MSBuildStaticGraphTester) which we're using to test out features of the MSBuild static graph feature (which BuildXL uses). @cdmihai can give a better description of what exactly to run, but it does point out what repos we've been building and changes are needed to build. 

For example building Orchard-Core:
* See https://github.com/microsoft/MSBuildStaticGraphTester/tree/master/projects/sdk/working/orchard-core
* Clone https://github.com/OrchardCMS/OrchardCore.git
* Checkout a660cf30a0ce12015d865d412471ed1632a2255a  (this is from the `repoInfo` file)
* Copy that traversal project (BuildXL can't real a `.sln` file) and the `config.dsc`
* Restore the sln first (`msbuild /t:Restore`)
* Run bxl.exe (after building this repo) in that folder and it should build.

There's a folder for Roslyn as well, but it's based off of a fork by @cdmihai and doesn't have the config file there (yet).

Don't take this as anything close to an end state and we'll work on having documentation for exactly this. But if you want to get started this gives you an idea of where we're at right now.

**Comment by smera** [comment]
*   There's a folder for Roslyn as well, but it's based off of a fork by @cdmihai<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcdmihai&data=02%7C01%7Csmera%40microsoft.com%7C27ee2b40498b492df3e908d6dafec4a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636937185093078835&sdata=9Yifxt4D8hlxOwYOXRf9g0qGupuGYRN6T%2FGhU8XFlTY%3D&reserved=0> and doesn't have the config file there (yet).
Small clarification, the folder ‘roslyn.bxl’ is pointing to the real Roslyn repo. Equivalent instructions apply to build it with bxl.

**Comment by jbayardo** [comment]
The example for MsBuild has been added at https://github.com/microsoft/BuildXL/tree/master/Examples/MsBuildHelloWorld

**Comment by dannyvv** [comment]
It seems this issue has been resolved. Closing the issue for now. Please let us know if this is not resolved satisfactory.
