### ISSUE TITLE
Unable to build from source: cl.exe not found

### ISSUE THREAD

**Issue by rongjiecomputer** [microsoft/BuildXL#370]
Here is the error message:

```
error DX0011: [PipFF41B2EE49D777E3, cl.exe (Microsoft C/C++ compiler), BuildXL.Sandbox.Windows, Detours.Lib.lib, {configuration:"release", platform:"x64"}] Process start failed with error code 00000002: File 'C:\Users\jie\GitHub\BuildXL\out\frontend\Nuget\pkgs\VisualCppTools.Community.VS2017Layout.14.11.25506\lib\native\bin\Hostx64\x64\cl.exe' was not found on disk. The tool is referred in 'C:\Users\jie\GitHub\BuildXL\Public\Src\Sandbox\Windows\Detours\Lib\Detours.dsc(17)'.
```

I went to check the `C:\Users\jie\GitHub\BuildXL\Out\frontend\Nuget\pkgs\VisualCppTools.Community.VS2017Layout.14.11.25506\lib\native` folder. there is only `atlmfc` folder, no `bin` folder.

Which folder should I delete or run any command to force `bxl/nuget` to redownload VS2017?

**Comment by dannyvv** [comment]
Just deleting that package should be enough.
`C:\Users\jie\GitHub\BuildXL\Out\frontend\Nuget\pkgs\VisualCppTools.Community.VS2017Layout.14.11.25506` would you mind giving that a try?

**Comment by rongjiecomputer** [comment]
@dannyvv I ended up having to delete all four `C:\Users\jie\GitHub\BuildXL\Out\frontend\Nuget\{cfgs,pkgs,specs,tmp}\VisualCppTools.Community.VS2017Layout.14.11.2550` to get the full VC++ toolset.

Before I tried that, `tmp` is the only folder that has full VC++ toolset, `cfgs,pkgs,specs` all only have files/info for atlmfc.
