### ISSUE TITLE
Two scripts in Shared\Scripts contain unicode BOM trash.

### ISSUE THREAD

**Issue by jwdonahue** [microsoft/BuildXL#376]
I just cloned the latest and ran bxl.cmd:

> bxl.cmd
Preparing to build.
'∩╗┐REM' is not recognized as an internal or external command,

Batch files should be stored as UTF-8, no BOM.

**Comment by jwdonahue** [comment]
I took a few moments to search for the scripts with BOM's:

BuildXLLkgVersion.cmd:1:∩╗┐REM @echo off
BuildXLLkgVersionPublic.cmd:1:∩╗┐REM @echo off

I'll issue a PR shortly.

**Comment by dannyvv** [comment]
Thanks for taking care of the pr as well!
