### ISSUE TITLE
build fails on windows10 1903

### ISSUE THREAD

**Issue by pedoc** [microsoft/BuildXL#469]
logs
[BuildXL.CacheMiss.log](https://github.com/microsoft/BuildXL/files/3289301/BuildXL.CacheMiss.log)

[BuildXL.log](https://github.com/microsoft/BuildXL/files/3289302/BuildXL.log)

[BuildXL.cache.log](https://github.com/microsoft/BuildXL/files/3289303/BuildXL.cache.log)

**Comment by pedoc** [comment]
BuildXL.err
```
E:\Study\BuildXL\Public\Sdk\Public\Protocols\Bond\bond.dsc(9,33): error DX11231: Property 'Contents' does not exist on type 'typeof Bond.CSharp'.
E:\Study\BuildXL\Public\Sdk\Public\Protocols\Bond\bond.dsc(10,41): error DX11231: Property 'Contents' does not exist on type 'typeof Bond.CSharp.osx-x64'.
E:\Study\BuildXL\Public\Src\Engine\Cache\BuildXL.Cache.dsc(27,44): error DX11231: Property 'pkg' does not exist on type 'typeof Bond.Core.CSharp'.
E:\Study\BuildXL\Public\Src\Engine\Dll\BuildXL.Engine.dsc(45,44): error DX11231: Property 'pkg' does not exist on type 'typeof Bond.Core.CSharp'.
error DX11230: One or more error occurred during workspace analysis. See output for more details.
```

**Comment by mpysson** [comment]
Sorry for taking so long to get back to you. I suspect this is a bug in the caching logic for generated nuget spec files. Could you try deleting this directory and retrying your build?

E:\Study\BuildXL\Out\frontend\Nuget\specs

**Comment by pedoc** [comment]
@mpysson 
thanks fou u reply.:)
yes,but not working.

**Comment by mpysson** [comment]
Hm, if deleting that nuget\specs directory didn't work could you provide the following?
1. The commit your repo is at
1. Build command you're trying to run
1. re-attach BuildXl.log file from current run
1. Attach bond.dsc or whatever .dsc files are referenced in the error you're seeing. (you may need to change extension to .txt for github)

**Comment by pedoc** [comment]
@mpysson hi,i am very sorry to reply so late.
after I got the latest code, I found that the error has been changed to something else.

![image](https://user-images.githubusercontent.com/6604230/63238053-36ee6280-c277-11e9-9292-7fbb4669ee80.png)

attachments
[20190819-112416.zip](https://github.com/microsoft/BuildXL/files/3514115/20190819-112416.zip)

thanks u work

**Comment by pedoc** [comment]
When I compile the "sln" file with "bxl /vs", I can't compile normally using visual studio 2019 preview 3.0.

![image](https://user-images.githubusercontent.com/6604230/63242609-88541d00-c28a-11e9-918b-cd241d78671f.png)

**Comment by castuardo** [comment]
To solve the compatibility problems, you need to install the plugin. Check the instructions here (Aquire the plugin section):

https://github.com/microsoft/BuildXL/blob/master/Documentation/Wiki/Installation.md

**Comment by pedoc** [comment]
thanks,but i have given up trying
