### ISSUE TITLE
Provide way of adjusting output format?

### ISSUE THREAD

**Issue by wjk** [microsoft/BuildXL#703]
When I run `bxl.sh` on macOS in the in-box Terminal app, the output is not formatted properly. See the following screenshot for an example:

<img width="682" alt="Screen Shot of BuildXL output" src="https://user-images.githubusercontent.com/1915951/62418715-0df68c80-b63e-11e9-86bb-83048e9a11b6.png">

Instead of overwriting the previous output (as happens on Windows), bits and pieces of old outputs scroll up the terminal buffer. There does not appear to be a flag I can use to disable whatever ANSI codes are emitted that attempt to do this. Is there anything I can try to attempt to fix this output issue? Thanks!

**Comment by dannyvv** [comment]
Thank you for reporting this issue. I have filed an internal workitem to track this. We have quite a few folks build on Macs and I haven't heard about this. 

We do have a flag that controls the overwrite beahvior. If you pass `/fancyconsole-` it should disable it.

**Comment by mpysson** [comment]
This was likely fixed by eef8e9a4b3db39f98c719921e475c73ebfa91d00 which addressed a similar issue on linux.
