### ISSUE TITLE
Pip fails due to .mui loading

### ISSUE THREAD

**Issue by bionicbeagle** [microsoft/BuildXL#878]
I grabbed head as of right now and I get lots of instances of the following when building. Perhaps this happens because I'm on a non-US version of Windows and end up pulling some localization packages which the file system tracking isn't expecting?

```[1:08] warning DX0268: [Pip47370E23192652B2, cl.exe (Microsoft C/C++ compiler), BuildXL.Sandbox.Windows, Core.nativesDll, {configuration:"debug", platform:"x64"}] Pip completed successfully, but with file monitoring violations. It will not be stored to the cache, since its declared inputs or outputs may be inaccurate.
[1:08] error DX0500: [Pip47370E23192652B2, cl.exe (Microsoft C/C++ compiler), BuildXL.Sandbox.Windows, Core.nativesDll, {configuration:"debug", platform:"x64"}] - Disallowed file accesses were detected (R = read, W = write):
Disallowed file accesses performed by: C:\github\BuildXL\out\frontend\Nuget\pkgs\VisualCppTools.Community.VS2017Layout.14.11.25506\lib\native\bin\Hostx64\x64\cl.exe
 R  C:\Program Files\WindowsApps\Microsoft.LanguageExperiencePacken-US_18362.9.10.0_neutral__8wekyb3d8bbwe\Windows\SYSTEM32\en-US\tzres.dll.mui

R  = Read
```

FWIW I ran into this when I tried BuildXL right at the time when it was announced as well, but figured it would get reported by someone else.

**Comment by edgarrs** [comment]
Your guess is right, the issue has to do with the location of the cl's runtime dependencies that may vary depending on the Windows locale. Our recommendation to workaround this is to add the following parameter to the bxl.exe execution:
/unsafe_GlobalUntrackedScopes: C:\Program Files\WindowsApps\Microsoft.LanguageExperiencePacken-US_18362.9.10.0_neutral__8wekyb3d8bbwe

**Comment by inforithmics** [comment]
This won't work because the Path has a space in it you have to escape the path. Because "" and ^ does not work for escaping you have to use the 8.3 path to escape it. With dir /x you see the short path name.

So on my Computer the Short Path name of "C:\Program files" is C:\progra~1 and I use following exclusion path and the compilation works now.

/unsafe_GlobalUntrackedScopes:C:\Progra~1\WindowsApps\Microsoft.LanguageExperiencePacken-US_18362.9.10.0_neutral__8wekyb3d8bbwe

**Comment by bionicbeagle** [comment]
This issue still occurs. It's possible to work around by whack-a-moling every .mui that ends up getting loaded. Building head as of today requires the following command line

`.\bxl.cmd -Minimal /unsafe_GlobalUntrackedScopes:C:\Progra~1\WindowsApps\Microsoft.LanguageExperiencePacken-US_18362.9.10.0_neutral__8wekyb3d8bbwe  /unsafe_GlobalUntrackedScopes:C:\Progra~1\WindowsApps\Microsoft.LanguageExperiencePacken-GB_18362.17.55.0_neutral__8wekyb3d8bbwe\Windows\SYSTEM32\en-GB\tzres.dll.mui /unsafe_GlobalUntrackedScopes:C:\Progra~1\WindowsApps\Microsoft.LanguageExperiencePacken-GB_18362.17.55.0_neutral__8wekyb3d8bbwe\Windows\System32\en-GB\crypt32.dll.mui /unsafe_GlobalUntrackedScopes:C:\Progra~1\WindowsApps\Microsoft.LanguageExperiencePacken-GB_18362.17.55.0_neutral__8wekyb3d8bbwe\Windows\System32\en-GB\winnlsres.dll.mui`

This doesn't strike me as a scalable solution, are there any plans to make BuildXL behave better on non-US operating system installs?

**Comment by mpysson** [comment]
@bionicbeagle - Can you sync to a commit at or newer than  54008a33101a3259deda2e71f433b621fcefd3ea and see if that alleviates the disallowed file access errors you are seeing?
